### ISSUE TITLE
Readme please

### ISSUE THREAD

**Issue by wsvincent** [jefftriplett/django-startproject#1]
Add some local set up instructions? 

- Install [docker-compose](https://docs.docker.com/compose/).

```
$ git clone git@github.com:jefftriplett/django-startproject.git
$ cd django-startproject
$ pipenv shell
$ pipenv install
$ docker build .
$ docker-compose up
```

Then personally I get complaints about `No module named 'config'` and also `pytest-django could not find a Django project (no manage.py file could be found). You must explicitly add your Django project to the Python path to have it picked up.`

**Comment by jefftriplett** [comment]
✅  Added some initial thoughts. I am probably going to roll this into something useful instead.
